In [2]:
# https://www.tensorflow.org/tutorials/quickstart/beginner

import tensorflow as tf
print("TensorFlow version:", tf.__version__)
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

TensorFlow version: 2.10.1
Num GPUs Available:  1


In [3]:
# Load a dataset
# Load and prepare the MNIST dataset. The pixel values of the images range from 0 through 255. 
# Scale these values to a range of 0 to 1 by dividing the values by 255.0. 
# This also converts the sample data from integers to floating-point numbers:

mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


In [4]:
# Build a machine learning model
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [5]:
# Sequential is useful for stacking layers where each layer has one input tensor and one output tensor. 
# Layers are functions with a known mathematical structure that can be reused and have trainable variables. 
# Most TensorFlow models are composed of layers. This model uses the Flatten, Dense, and Dropout layers.

# For each example, the model returns a vector of logits or log-odds scores, one for each class.
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.51773024,  0.18127513,  0.40085638,  0.00839549,  0.59502363,
        -0.30197018,  0.29418075,  0.58713317, -0.18971702, -0.81171703]],
      dtype=float32)

In [6]:
# The tf.nn.softmax function converts these logits to probabilities for each class:
tf.nn.softmax(predictions).numpy()

array([[0.13596414, 0.0971189 , 0.12096693, 0.0817002 , 0.14689007,
        0.05990085, 0.10872716, 0.1457356 , 0.06701684, 0.0359793 ]],
      dtype=float32)

In [7]:
# Define a loss function for training using losses.SparseCategoricalCrossentropy:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
# The loss function takes a vector of ground truth values and a vector of logits and returns a scalar loss for each example. 
# This loss is equal to the negative log probability of the true class: The loss is zero if the model is sure of the correct class.

# This untrained model gives probabilities close to random (1/10 for each class), so the initial loss should be close to -tf.math.log(1/10) ~= 2.3.
loss_fn(y_train[:1], predictions).numpy()

2.8150647

In [9]:
# Before you start training, configure and compile the model using Keras Model.compile. 
# Set the optimizer class to adam, set the loss to the loss_fn function you defined earlier, 
# and specify a metric to be evaluated for the model by setting the metrics parameter to accuracy.
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [10]:
# Train and evaluate your model
# Use the Model.fit method to adjust your model parameters and minimize the loss:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.3031 - accuracy: 0.9119
Epoch 2/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1466 - accuracy: 0.9567
Epoch 3/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1095 - accuracy: 0.9663
Epoch 4/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0890 - accuracy: 0.9728
Epoch 5/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0760 - accuracy: 0.9765


In [11]:
# The Model.evaluate method checks the model's performance, usually on a validation set or test set.
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0749 - accuracy: 0.9768 - 924ms/epoch - 3ms/step


[0.07489185780286789, 0.9768000245094299]

In [12]:
# The image classifier is now trained to ~98% accuracy on this dataset. To learn more, read the TensorFlow tutorials.

# If you want your model to return a probability, you can wrap the trained model, and attach the softmax to it:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[5.60082617e-06, 1.08991216e-08, 3.28499882e-05, 2.22538525e-04,
        3.69246821e-11, 2.59061068e-07, 1.80446554e-12, 9.99683022e-01,
        8.05079878e-07, 5.49294418e-05],
       [1.30892033e-07, 2.08829442e-05, 9.99931455e-01, 1.48248273e-05,
        2.44840726e-18, 3.26104382e-05, 1.38876160e-07, 1.67643728e-14,
        4.46330510e-08, 1.83612010e-15],
       [6.07859590e-07, 9.99441445e-01, 2.12906198e-05, 1.00424609e-06,
        1.76391022e-05, 1.90953938e-06, 2.32312705e-05, 3.93400493e-04,
        9.89242690e-05, 6.06548042e-07],
       [9.99990940e-01, 1.81564430e-10, 1.77114032e-07, 1.98709245e-08,
        2.43709426e-08, 2.66545476e-06, 4.23389474e-06, 1.22934239e-06,
        1.62316294e-09, 6.86229157e-07],
       [9.19045397e-06, 5.73718983e-09, 4.64682535e-06, 1.09408404e-07,
        9.98803973e-01, 5.00637725e-07, 1.84538258e-05, 7.05435523e-05,
        1.62399158e-06, 1.09100842e-03]], dtype=float32)>

In [ ]:
# Conclusion
# Congratulations! You have trained a machine learning model using a prebuilt dataset using the Keras API.